[package]
name = "carapace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dsa = "0.6.2"
num = "0.4.1"
rand = "0.8.5"
rsa = "0.9.3"
sha1 = "0.10.6"